server:
  port: 8081

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/auth
  realm: TestRealm
  resource: test
#  ssl-required: external
  public-client: true
  principal-attribute: preferred_username
#  use-resource-role-mappings: true
#  pkce: true
